export const users = [
    {
        "id": 1,
        "firstName": "Deepak",
        "lastName": "Singh",
        "age": 50,
        "phone": "+63 791 675 8914",
        "username": "atuny0",
        "image": "https://robohash.org/hicveldicta.png",
    },
    {
        "id": 2,
        "firstName": "John",
        "lastName": "Smith",
        "age": 45,
        "phone": "+1 123 456 7890",
        "username": "jsmith",
        "image": "https://robohash.org/laboriosamfacilisrem.png",
    },
    {
        "id": 3,
        "firstName": "Michael",
        "lastName": "Williams",
        "age": 55,
        "phone": "+44 789 345 1230",
        "username": "mwilliams",
        "image": "https://robohash.org/cupiditatererumquos.png",
    },
    {
        "id": 4,
        "firstName": "Jessica",
        "lastName": "Brown",
        "age": 35,
        "phone": "+65 876 543 2101",
        "username": "jbrown",
        "image": "https://robohash.org/quiaharumsapiente.png",
    },
    {
        "id": 5,
        "firstName": "David",
        "lastName": "Garcia",
        "age": 40,
        "phone": "+567 890 234 1256",
        "username": "dgarcia",
        "image": "https://robohash.org/adverovelit.png",
    },
    {
        "id": 6,
        "firstName": "Maria",
        "lastName": "Rodriguez",
        "age": 30,
        "phone": "+91 234 567 8901",
        "username": "mrodriguez",
        "image": "https://robohash.org/facilisdignissimosdolore.png",
    },

]